spring.application.name=chat-ai

spring.autoconfigure.exclude=\
  org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration,\
  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration

#spring.ai.openai.base-url=https://api.openai.com
#spring.ai.openai.api-key=${OPENAI_API_KEY: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}
# spring.ai.openai.chat.options.model=gpt-5
# Between 0 to 1.
# higher number -> more creative and random
# lower number -> more deterministic
# gpt-5 supports temperature=1 only
#spring.ai.openai.chat.options.temperature=1

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:latest
spring.ai.ollama.chat.options.temperature=0.7

spring.ai.mcp.client.sse.connections.chatbot.url=http://localhost:8181
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

## CORS CONFIG
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
cors.allowed-methods=${CORS_ALLOWED_METHODS:POST,GET,PUT,OPTIONS,DELETE,PATCH}
cors.max-age=${CORS_MAX_AGE:3600}
cors.allowed-headers=${CORS_ALLOWED_HEADERS:*}
cors.exposed-headers=${CORS_EXPOSED_HEADERS:*}